### PR TITLE
fix: Infrastructure page content width

### LINKED ISSUE #1241: Infrastructure monitor page content is wider than Monitors or Pagespeed
Comparison: 

image

vs

image

### PR DESCRIPTION
**Pull request by peterpardo**
### Summary
This PR fixes the issue of the page content width of the **Infrastructure Page**, the route is `/infrastructure`, wherein its page content width is wider than the other pages; resulting also in making the sidebar width smaller.

### Changes Made
- Updated the **Infrastructure Page** to use `div` element instead of the `main` element as the main container for the page content

### Related Issues/s
Closes #1241 

### Screenshots
**Before:**
issue1241-before

**After:**
issue1241-after

### Additional Context
N/A

### CODE REVIEW

**Comment by peterpardo** [comment]
> Looks good @peterpardo - that now has exactly the same width as other menu items, right ?

Yep! Here is a quick demo:

https://github.com/user-attachments/assets/e8bbb6fe-ac96-4053-8730-cfe306a7e624

**Comment by gorkem-bwl** [comment]
Looks good. If you want other quick UI fixes/tasks, I can suggest a few of those.

**Review by marcelluscaio — APPROVED** [review]
Thanks for you contribution @peterpardo

**Review by ajhollid — APPROVED** [review]

**Comment by peterpardo** [comment]
> Looks good. If you want other quick UI fixes/tasks, I can suggest a few of those.

Yeah sure! I'd be happy to help.

**Pull request merged**
