### PR TITLE
Changed the avatar color to checkmate blue color

### PR DESCRIPTION
**Pull request by sha-linimoorthy**
Issue #1402
To use Checkmate blue color for avatar background color has been changed.

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
@sha-linimoorthy there were a lot of checkboxes in the PR template. Did you see them or remove them? 

Example: https://github.com/bluewave-labs/checkmate/pull/1406

**Comment by sha-linimoorthy** [comment]
> @sha-linimoorthy there were a lot of checkboxes in the PR template. Did you see them or remove them?
> 
> Example: #1406

I didn't remove them.

**Comment by gorkem-bwl** [comment]
> > @sha-linimoorthy there were a lot of checkboxes in the PR template. Did you see them or remove them?
> > Example: #1406
> 
> I didn't remove them.

That's interesting. So in this case they weren't visible in your PR right?

**Comment by sha-linimoorthy** [comment]
> > > @sha-linimoorthy there were a lot of checkboxes in the PR template. Did you see them or remove them?
> > > Example: #1406
> > 
> > 
> > I didn't remove them.
> 
> That's interesting. So in this case they weren't visible in your PR right?

yes, it isn't.

**Comment by sha-linimoorthy** [comment]
> No hardcode values, please use the theme

Okay

**Review by ajhollid — APPROVED** [review]
Thanks for making the requested changes :+1:

**Pull request merged**
