### PR TITLE
Hamburger Icon button rounded

### PR DESCRIPTION
**Pull request by rafeyrana**
Fixes: #1483

Round button demo:
round-button

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
UI wise looks good. I believe the bg of the theme selector don't conflict with your bg ? 

image

**Comment by rafeyrana** [comment]
I am not sure what you mean by that. The screenshot was taken while hovering over the controls icon to show shape. It has a dark grey background on hover for both icons (theme selector and controls) in dark mode and the light grey in light mode. No background conflict and seemed all good to me. Thanks!

**Comment by gorkem-bwl** [comment]
> I am not sure what you mean by that. The screenshot was taken while hovering over the controls icon to show shape. It has a dark grey background on hover for both icons (theme selector and controls) in dark mode and the light grey in light mode. No background conflict and seemed all good to me. Thanks!

Perfect. I was curious about overlapping - if they are not there, we are good to go here!

**Comment by rafeyrana** [comment]
yup confirmed no overlaps, ready to merge

**Review by ajhollid — APPROVED** [review]

**Pull request merged**
