### PR TITLE
Move certificate expiry to a card #1327

### PR DESCRIPTION
**Pull request by aroy114**
## Describe your changes
Moved certificate expiry to a card.
## Issue Number
#1327  

## Please ensure all items are checked off before requesting a review:
- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I have labelled the PR correctly.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached this to PR if there is a UI change.

## Screenshot
image

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
Looks good @Anand-Royy - can you add the year to this section too? Like "Feb 24, 2025 3:00AM" ?

**Comment by Anand-Royy** [comment]
> Looks good @Anand-Royy - can you add the year to this section too, if you have this information from the backend? Like "Feb 24, 2025 3:00AM" ?

@gorkem-bwl  does this look good?

image

**Comment by gorkem-bwl** [comment]
Looks good. Thanks!

**Review by ajhollid — APPROVED** [review]
Looks good to me, thank you for your contribution!

**Pull request merged**
