### PR TITLE
Added gap between label and inputs with consistent gaps #1270

### PR DESCRIPTION
**Pull request by Shaikh-Mudassir**
I have made the necessary changes to the code, ensuring consistent spacing across all panels using a centralized GAP_SIZE constant. However, I am unable to fully verify the changes locally since the client requires login. Please review the code changes and let me know if any further adjustments are needed.

Issue number : #1270
This PR addresses the issue  #1270 

- [ Yes] I have performed a self-review of my code.
- [Yes ] I have included the issue # in the PR.
- [ Yes] I have labelled the PR correctly.
- [ Yes] My PR is granular and targeted to one specific feature only.

### CODE REVIEW

**Comment by marcelluscaio** [comment]
Thanks for your contribution @Shaikh-Mudassir . Do you have prettier installed? Our prettierrc should enforce styles, but the diff is still too big, making it difficult to track the changes

**Comment by Shaikh-Mudassir** [comment]
I have already added comments for your review. If you still encounter any issues or challenges, please let me know, and I will make a new commit after using Prettier.

**Comment by marcelluscaio** [comment]
Yes, please, try to submit a diff that highlights only the parts of the code that you changed

**Comment by ajhollid** [comment]
> I have already added comments for your review. If you still encounter any issues or challenges, please let me know, and I will make a new commit after using Prettier.

@Shaikh-Mudassir yes please do reformat with Prettier so the formatting is consistent, otherwise we're just going to have to open a new PR to reformat anyways.

**Comment by Shaikh-Mudassir** [comment]
I have formatted everything with prettier. If you still encounter issues finding the changes i would suggest searching the term "SPACING_GAP" which will take you to all the changes that i made.

**Comment by ajhollid** [comment]
Hi @Shaikh-Mudassir ,

Thanks for formatting, however since your previous commit already includes the incorrect formatting the diff is unfortunately still too large for us to properly reivew htis PR.

My suggestion would be to close this PR, create a new branch from develop that has the proper formatting, make your changes, and commit.

**Comment by Shaikh-Mudassir** [comment]
@ajhollid Thank You for your response.  I will be creating a new branch and commit once again after closing thid PR.

**Comment by ajhollid** [comment]
> @ajhollid Thank You for your response.  I will be creating a new branch and commit once again. 

Awesome, thanks for doing that 👌

**Pull request closed without merging**
